/**
 * Countries for the editor onboarding: name, iso2 and dial code, one list,
 * alphabetical. The flag is derived from the iso2 at render (regional
 * indicator codepoints), so nothing here stores an emoji. Lowercase names on
 * purpose, house voice. Pure data, safe on the client.
 */

export type Country = { name: string; iso: string; dial: string };

export function flagEmoji(iso: string): string {
  return String.fromCodePoint(
    ...[...iso.toUpperCase()].map((c) => 127397 + c.charCodeAt(0))
  );
}

export const COUNTRIES: readonly Country[] = [
  { name: "afghanistan", iso: "AF", dial: "+93" },
  { name: "albania", iso: "AL", dial: "+355" },
  { name: "algeria", iso: "DZ", dial: "+213" },
  { name: "argentina", iso: "AR", dial: "+54" },
  { name: "armenia", iso: "AM", dial: "+374" },
  { name: "australia", iso: "AU", dial: "+61" },
  { name: "austria", iso: "AT", dial: "+43" },
  { name: "azerbaijan", iso: "AZ", dial: "+994" },
  { name: "bahrain", iso: "BH", dial: "+973" },
  { name: "bangladesh", iso: "BD", dial: "+880" },
  { name: "belarus", iso: "BY", dial: "+375" },
  { name: "belgium", iso: "BE", dial: "+32" },
  { name: "bolivia", iso: "BO", dial: "+591" },
  { name: "bosnia and herzegovina", iso: "BA", dial: "+387" },
  { name: "botswana", iso: "BW", dial: "+267" },
  { name: "brazil", iso: "BR", dial: "+55" },
  { name: "bulgaria", iso: "BG", dial: "+359" },
  { name: "cambodia", iso: "KH", dial: "+855" },
  { name: "cameroon", iso: "CM", dial: "+237" },
  { name: "canada", iso: "CA", dial: "+1" },
  { name: "chile", iso: "CL", dial: "+56" },
  { name: "china", iso: "CN", dial: "+86" },
  { name: "colombia", iso: "CO", dial: "+57" },
  { name: "costa rica", iso: "CR", dial: "+506" },
  { name: "croatia", iso: "HR", dial: "+385" },
  { name: "cuba", iso: "CU", dial: "+53" },
  { name: "cyprus", iso: "CY", dial: "+357" },
  { name: "czechia", iso: "CZ", dial: "+420" },
  { name: "denmark", iso: "DK", dial: "+45" },
  { name: "dominican republic", iso: "DO", dial: "+1" },
  { name: "ecuador", iso: "EC", dial: "+593" },
  { name: "egypt", iso: "EG", dial: "+20" },
  { name: "el salvador", iso: "SV", dial: "+503" },
  { name: "estonia", iso: "EE", dial: "+372" },
  { name: "ethiopia", iso: "ET", dial: "+251" },
  { name: "finland", iso: "FI", dial: "+358" },
  { name: "france", iso: "FR", dial: "+33" },
  { name: "georgia", iso: "GE", dial: "+995" },
  { name: "germany", iso: "DE", dial: "+49" },
  { name: "ghana", iso: "GH", dial: "+233" },
  { name: "greece", iso: "GR", dial: "+30" },
  { name: "guatemala", iso: "GT", dial: "+502" },
  { name: "honduras", iso: "HN", dial: "+504" },
  { name: "hong kong", iso: "HK", dial: "+852" },
  { name: "hungary", iso: "HU", dial: "+36" },
  { name: "iceland", iso: "IS", dial: "+354" },
  { name: "india", iso: "IN", dial: "+91" },
  { name: "indonesia", iso: "ID", dial: "+62" },
  { name: "iran", iso: "IR", dial: "+98" },
  { name: "iraq", iso: "IQ", dial: "+964" },
  { name: "ireland", iso: "IE", dial: "+353" },
  { name: "israel", iso: "IL", dial: "+972" },
  { name: "italy", iso: "IT", dial: "+39" },
  { name: "jamaica", iso: "JM", dial: "+1" },
  { name: "japan", iso: "JP", dial: "+81" },
  { name: "jordan", iso: "JO", dial: "+962" },
  { name: "kazakhstan", iso: "KZ", dial: "+7" },
  { name: "kenya", iso: "KE", dial: "+254" },
  { name: "kosovo", iso: "XK", dial: "+383" },
  { name: "kuwait", iso: "KW", dial: "+965" },
  { name: "kyrgyzstan", iso: "KG", dial: "+996" },
  { name: "laos", iso: "LA", dial: "+856" },
  { name: "latvia", iso: "LV", dial: "+371" },
  { name: "lebanon", iso: "LB", dial: "+961" },
  { name: "libya", iso: "LY", dial: "+218" },
  { name: "lithuania", iso: "LT", dial: "+370" },
  { name: "luxembourg", iso: "LU", dial: "+352" },
  { name: "malaysia", iso: "MY", dial: "+60" },
  { name: "maldives", iso: "MV", dial: "+960" },
  { name: "malta", iso: "MT", dial: "+356" },
  { name: "mexico", iso: "MX", dial: "+52" },
  { name: "moldova", iso: "MD", dial: "+373" },
  { name: "mongolia", iso: "MN", dial: "+976" },
  { name: "montenegro", iso: "ME", dial: "+382" },
  { name: "morocco", iso: "MA", dial: "+212" },
  { name: "myanmar", iso: "MM", dial: "+95" },
  { name: "nepal", iso: "NP", dial: "+977" },
  { name: "netherlands", iso: "NL", dial: "+31" },
  { name: "new zealand", iso: "NZ", dial: "+64" },
  { name: "nicaragua", iso: "NI", dial: "+505" },
  { name: "nigeria", iso: "NG", dial: "+234" },
  { name: "north macedonia", iso: "MK", dial: "+389" },
  { name: "norway", iso: "NO", dial: "+47" },
  { name: "oman", iso: "OM", dial: "+968" },
  { name: "pakistan", iso: "PK", dial: "+92" },
  { name: "palestine", iso: "PS", dial: "+970" },
  { name: "panama", iso: "PA", dial: "+507" },
  { name: "paraguay", iso: "PY", dial: "+595" },
  { name: "peru", iso: "PE", dial: "+51" },
  { name: "philippines", iso: "PH", dial: "+63" },
  { name: "poland", iso: "PL", dial: "+48" },
  { name: "portugal", iso: "PT", dial: "+351" },
  { name: "puerto rico", iso: "PR", dial: "+1" },
  { name: "qatar", iso: "QA", dial: "+974" },
  { name: "romania", iso: "RO", dial: "+40" },
  { name: "russia", iso: "RU", dial: "+7" },
  { name: "rwanda", iso: "RW", dial: "+250" },
  { name: "saudi arabia", iso: "SA", dial: "+966" },
  { name: "senegal", iso: "SN", dial: "+221" },
  { name: "serbia", iso: "RS", dial: "+381" },
  { name: "singapore", iso: "SG", dial: "+65" },
  { name: "slovakia", iso: "SK", dial: "+421" },
  { name: "slovenia", iso: "SI", dial: "+386" },
  { name: "somalia", iso: "SO", dial: "+252" },
  { name: "south africa", iso: "ZA", dial: "+27" },
  { name: "south korea", iso: "KR", dial: "+82" },
  { name: "spain", iso: "ES", dial: "+34" },
  { name: "sri lanka", iso: "LK", dial: "+94" },
  { name: "sudan", iso: "SD", dial: "+249" },
  { name: "sweden", iso: "SE", dial: "+46" },
  { name: "switzerland", iso: "CH", dial: "+41" },
  { name: "syria", iso: "SY", dial: "+963" },
  { name: "taiwan", iso: "TW", dial: "+886" },
  { name: "tajikistan", iso: "TJ", dial: "+992" },
  { name: "tanzania", iso: "TZ", dial: "+255" },
  { name: "thailand", iso: "TH", dial: "+66" },
  { name: "trinidad and tobago", iso: "TT", dial: "+1" },
  { name: "tunisia", iso: "TN", dial: "+216" },
  { name: "turkey", iso: "TR", dial: "+90" },
  { name: "turkmenistan", iso: "TM", dial: "+993" },
  { name: "uganda", iso: "UG", dial: "+256" },
  { name: "ukraine", iso: "UA", dial: "+380" },
  { name: "united arab emirates", iso: "AE", dial: "+971" },
  { name: "united kingdom", iso: "GB", dial: "+44" },
  { name: "united states", iso: "US", dial: "+1" },
  { name: "uruguay", iso: "UY", dial: "+598" },
  { name: "uzbekistan", iso: "UZ", dial: "+998" },
  { name: "venezuela", iso: "VE", dial: "+58" },
  { name: "vietnam", iso: "VN", dial: "+84" },
  { name: "yemen", iso: "YE", dial: "+967" },
  { name: "zambia", iso: "ZM", dial: "+260" },
  { name: "zimbabwe", iso: "ZW", dial: "+263" },
] as const;

/** GMT offsets for the time zone picker, whole hours plus the real halves. */
export const TIMEZONES: readonly string[] = [
  "gmt-11", "gmt-10", "gmt-9", "gmt-8", "gmt-7", "gmt-6", "gmt-5", "gmt-4",
  "gmt-3", "gmt-2", "gmt-1", "gmt+0", "gmt+1", "gmt+2", "gmt+3", "gmt+3:30",
  "gmt+4", "gmt+4:30", "gmt+5", "gmt+5:30", "gmt+5:45", "gmt+6", "gmt+6:30",
  "gmt+7", "gmt+8", "gmt+9", "gmt+9:30", "gmt+10", "gmt+11", "gmt+12",
  "gmt+13", "gmt+14",
];

/** The browser's own offset as one of the list's values, for the default. */
export function localTimezone(): string {
  const mins = -new Date().getTimezoneOffset();
  const sign = mins < 0 ? "-" : "+";
  const abs = Math.abs(mins);
  const h = Math.floor(abs / 60);
  const m = abs % 60;
  const label = `gmt${sign}${h}${m ? `:${String(m).padStart(2, "0")}` : ""}`;
  return TIMEZONES.includes(label) ? label : "gmt+0";
}
